### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by midgithub** [hiram3512/ExcelToProtobuf_csharp#1]
建议 Excel的操作库不要使用microoffice的Excel库，不同版本不兼容。
换npoi 库操作excel。
其他很棒

**Comment by hiram3512** [comment]
这个版本库采用C#开发,默认用户安装了.net有roslyn编译器,已规划用python重构,不依赖平台.谢谢贡献建议,如果有兴趣参与一起开发可以邮件hiramtan@live.com
