### ISSUE TITLE
excel超过100行，就阻塞... .dat生成不出来

### ISSUE THREAD

**Issue by EricDDK** [hiram3512/ExcelToProtobuf_csharp#2]
试了一下就完全卡死了，而且非常慢。
用的最新release的exe

**Comment by hiram3512** [comment]
这个版本库采用C#开发,默认用户安装了.net有roslyn编译器,已规划用python重构,不依赖平台.谢谢贡献建议,如果有兴趣参与一起开发可以邮件hiramtan@live.com
